In [1]:
import numpy as np

In [2]:
A = np.array([1, 2, 3, 4])
print(A)

print(np.ndim(A))

print(A.shape)
print(A.shape[0])



[1 2 3 4]
1
(4,)
4


In [3]:
B = np.array([[1, 2], [3, 4], [5, 6]])  
print(B)

print(np.ndim(B))

print(B.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


## Dot Product

In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))

[[19 22]
 [43 50]]


In [6]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A.shape
B = np.array([[1, 2], [3, 4], [5, 6]])
B.shape

print(np.dot(A, B))

[[22 28]
 [49 64]]


In [7]:
C = np.array([7, 8])
print(C.shape)

print(np.dot(B, C))

[23 53 83]


In [11]:
W  = np.array([[1, 3, 5], [2, 4, 6]])

YY = np.dot(C, W)
print(YY)

[23 53 83]
